### ISSUE TITLE
Is Moose needed as a prerequisite?

### ISSUE THREAD

**Issue by robrwo** [davorg/moox-role-json_ld#14]
Shouldn't Moose be a test prereq?

**Comment by JJ** [comment]
It's already a build prereq. What do you mean?

**Comment by robrwo** [comment]
It's not needed for building or running, only for tests. It should be a recommended test prereq so that the test skips if Moose is not installed.

**Comment by davorg** [comment]
Does ExtUtils::MakeMaker have a way to declare recommended test prereqs?

**Comment by robrwo** [comment]
Well, at the minimum Moose could be moved from PREREQ_PM to TEST_REQUIRES.

But you may be able to change the META_MERGE for
```perl
  prereqs => {
    "recommends" => {  "Moose" => 0 },
  }
```
